---
output:
  html_document: default
---

Blockchain technology and cryptocurrency have gained popularity through social media platforms such as Reddit. This application attempts to visualize relationships between Reddit's r/Ripple sub-reddit and XRP price during the time period July 30th, 2018 and February 1, 2019.  The project seeks to answer the following questions:


1. Do the number of sub-reddit posts correlate with future price change? <br />
  a. Does daily post volume relate to next day price change? <br />
  b. Does weekly post volume relate to next week price change? <br />

2. Does sub-reddit post sentiment have any correlation with future price change? <br />
  a. Does daily average post sentiment relate to next day price change? <br />
  b. Does weekly average post sentiment relate to next week price change? <br />

3. Are particular words more prevalent in posts prior to a price increase? <br />
  a. What words are most prevalent the day before a daily price increase? <br />
  b. What words are most prevalent the week before a weekly price increase? <br />
  
4. Are particular words more prevalent in posts prior to a price decrease? <br />
  a. What words are most prevalent the day before a daily price decrease? <br />
  b. What words are most prevalent the week before a weekly price decrease? <br />

Pearson correlation is used to measure correlation and statistical significance is evaluated.<br /> 
Data used for this visualization application were scraped using Selenium.<br /> 
All scraping was performed on "https://www.reddit.com/r/Ripple/" sub-reddit constrained to thread titles "Daily Ripple/XRP Discussion Thread ##/##/#### [Questions and Price Predictions]"








 

