---
output:
  html_document: default
---

Blockchain technology and cryptocurrency have gained popularity through social media platforms such as Reddit. This application attempts to visualize relationships between Reddit's r/Ripple sub-reddit and XRP price during the time period July 30th, 2018 and February 1, 2019.  The project seeks to answer the following questions:


1. Do the number of sub-reddit posts correlate with future price change? 
  a. Does daily post volume relate to next day price change?
  b. Does weekly post volume relate to next week price change?

2. Does sub-reddit post sentiment have any correlation with future price change?
  a. Does daily average post sentiment relate to next day price change?
  b. Does weekly average post sentiment relate to next week price change?

3. Are particular words more prevalent in posts prior to a price increase?
  a. What words are most prevalent the day before a daily price increase?
  b. What words are most prevalent the week before a weekly price increase?
  
4. Are particular words more prevalent in posts prior to a price decrease?
  a. What words are most prevalent the day before a daily price decrease?
  b. What words are most prevalent the week before a weekly price decrease?

Pearson correlation is used to measure correlation and statistical significance is evaluated.

Data used for this visualization application were scraped using Selenium.  All scraping was performed on "https://www.reddit.com/r/Ripple/" sub-reddit constrained to thread titles "Daily Ripple/XRP Discussion Thread ##/##/#### [Questions and Price Predictions]"








 

